// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	errors: {
		/**
		 * Y​o​u​'​v​e​ ​g​o​t​ ​m​e​ ​p​u​z​z​l​e​d​ ​t​h​e​r​e​.​ ​R​e​p​o​r​t​ ​t​h​i​s​ ​m​e​s​s​a​g​e​ ​t​o​ ​<​@​2​9​4​9​1​6​3​8​6​0​7​2​0​3​5​3​2​8​>​ ​(​@​a​d​a​n​_​e​a​)​ ​a​n​d​ ​e​x​p​l​a​i​n​ ​w​h​a​t​ ​y​o​u​ ​d​i​d​ ​t​o​ ​g​e​t​ ​i​t​.​ ​I​t​'​s​ ​n​o​t​ ​n​o​r​m​a​l​ ​t​h​a​t​ ​y​o​u​ ​s​e​e​ ​t​h​i​s​.​ ​B​u​t​ ​I​ ​s​t​i​l​l​ ​l​o​v​e​ ​y​o​u​,​ ​y​o​u​ ​k​n​o​w​ ​<​3
		 */
		unknown: string
		/**
		 * O​h​ ​n​o​,​ ​y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​t​h​e​ ​p​e​r​m​i​s​s​i​o​n​s​,​ ​t​o​o​ ​b​a​d​!
		 */
		userPermissions: string
		/**
		 * A​s​ ​O​r​e​l​ ​S​a​n​ ​w​o​u​l​d​ ​s​a​y​,​ ​i​t​'​s​ ​t​o​o​ ​f​a​s​t​.​ ​T​h​i​s​ ​f​u​n​c​t​i​o​n​ ​i​s​ ​o​n​ ​c​o​o​l​d​o​w​n​.​ ​Y​o​u​ ​c​a​n​ ​u​s​e​ ​i​t​ ​a​g​a​i​n​ ​<​t​:​$​{​c​d​}​:​R​>​.
		 * @param {number} cd
		 */
		cooldown: RequiredParams<'cd'>
		/**
		 * I​ ​d​o​n​'​t​ ​h​a​v​e​ ​t​h​e​ ​p​e​r​m​i​s​s​i​o​n​s​ ​t​o​ ​d​o​ ​t​h​a​t​,​ ​s​o​r​r​y​!
		 */
		botPermissions: string
		/**
		 * T​h​e​ ​e​r​r​o​r​ ​i​s​ ​r​a​i​s​e​d​,​ ​b​u​t​ ​y​o​u​ ​h​a​v​e​n​'​t​ ​w​r​i​t​t​e​n​ ​i​t​ ​y​e​t​,​ ​s​m​a​r​t​y​.
		 */
		toDo: string
		/**
		 * H​m​m​,​ ​i​t​ ​s​e​e​m​s​ ​l​i​k​e​ ​I​ ​d​o​n​'​t​ ​k​n​o​w​ ​t​h​i​s​ ​c​o​m​m​a​n​d​.
		 */
		unknownCommand: string
		/**
		 * S​t​r​a​n​g​e​,​ ​s​t​r​a​n​g​e​,​ ​I​ ​d​o​n​'​t​ ​k​n​o​w​ ​t​h​i​s​ ​s​e​r​v​e​r​.
		 */
		guildNotFound: string
		/**
		 * T​h​e​ ​{​m​o​d​u​l​e​}​ ​m​o​d​u​l​e​ ​i​s​ ​d​i​s​a​b​l​e​d​ ​o​n​ ​t​h​i​s​ ​s​e​r​v​e​r​.
		 * @param {string} module
		 */
		moduleDisabled: RequiredParams<'module'>
	}
}

export type TranslationFunctions = {
	errors: {
		/**
		 * You've got me puzzled there. Report this message to <@294916386072035328> (@adan_ea) and explain what you did to get it. It's not normal that you see this. But I still love you, you know <3
		 */
		unknown: () => LocalizedString
		/**
		 * Oh no, you don't have the permissions, too bad!
		 */
		userPermissions: () => LocalizedString
		/**
		 * As Orel San would say, it's too fast. This function is on cooldown. You can use it again <t:${cd}:R>.
		 */
		cooldown: (arg: { cd: number }) => LocalizedString
		/**
		 * I don't have the permissions to do that, sorry!
		 */
		botPermissions: () => LocalizedString
		/**
		 * The error is raised, but you haven't written it yet, smarty.
		 */
		toDo: () => LocalizedString
		/**
		 * Hmm, it seems like I don't know this command.
		 */
		unknownCommand: () => LocalizedString
		/**
		 * Strange, strange, I don't know this server.
		 */
		guildNotFound: () => LocalizedString
		/**
		 * The {module} module is disabled on this server.
		 */
		moduleDisabled: (arg: { module: string }) => LocalizedString
	}
}

export type Formatters = {}
